// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package sd.adaa.codeide.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object IdeApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Setup / bootstrap status.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SetupStatus (
  val ready: Boolean,
  val bootstrapVersion: String? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetupStatus {
      val ready = pigeonVar_list[0] as Boolean
      val bootstrapVersion = pigeonVar_list[1] as String?
      val error = pigeonVar_list[2] as String?
      return SetupStatus(ready, bootstrapVersion, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ready,
      bootstrapVersion,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SetupStatus
    return IdeApiPigeonUtils.deepEquals(this.ready, other.ready) && IdeApiPigeonUtils.deepEquals(this.bootstrapVersion, other.bootstrapVersion) && IdeApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.ready)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.bootstrapVersion)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "SetupStatus(ready=$ready, bootstrapVersion=$bootstrapVersion, error=$error)"
  }
}

/**
 * A runtime (php / node / python / ...) inspected on the host.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RuntimeInfo (
  val id: String,
  val displayName: String,
  val version: String? = null,
  val installed: Boolean,
  val executable: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RuntimeInfo {
      val id = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val version = pigeonVar_list[2] as String?
      val installed = pigeonVar_list[3] as Boolean
      val executable = pigeonVar_list[4] as String?
      return RuntimeInfo(id, displayName, version, installed, executable)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      version,
      installed,
      executable,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RuntimeInfo
    return IdeApiPigeonUtils.deepEquals(this.id, other.id) && IdeApiPigeonUtils.deepEquals(this.displayName, other.displayName) && IdeApiPigeonUtils.deepEquals(this.version, other.version) && IdeApiPigeonUtils.deepEquals(this.installed, other.installed) && IdeApiPigeonUtils.deepEquals(this.executable, other.executable)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.id)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.displayName)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.version)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.installed)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.executable)
    return result
  }
  override fun toString(): String {
    return "RuntimeInfo(id=$id, displayName=$displayName, version=$version, installed=$installed, executable=$executable)"
  }
}

/**
 * A managed background process.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProcessInfo (
  val pid: String,
  val command: String,
  val cwd: String? = null,
  val exitCode: Long? = null,
  val status: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessInfo {
      val pid = pigeonVar_list[0] as String
      val command = pigeonVar_list[1] as String
      val cwd = pigeonVar_list[2] as String?
      val exitCode = pigeonVar_list[3] as Long?
      val status = pigeonVar_list[4] as String?
      return ProcessInfo(pid, command, cwd, exitCode, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pid,
      command,
      cwd,
      exitCode,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProcessInfo
    return IdeApiPigeonUtils.deepEquals(this.pid, other.pid) && IdeApiPigeonUtils.deepEquals(this.command, other.command) && IdeApiPigeonUtils.deepEquals(this.cwd, other.cwd) && IdeApiPigeonUtils.deepEquals(this.exitCode, other.exitCode) && IdeApiPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.pid)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.command)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.cwd)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.exitCode)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.status)
    return result
  }
  override fun toString(): String {
    return "ProcessInfo(pid=$pid, command=$command, cwd=$cwd, exitCode=$exitCode, status=$status)"
  }
}

/**
 * Request to spawn a managed process.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProcessRequest (
  val command: String,
  val args: List<String>,
  val cwd: String? = null,
  val environment: Map<String, String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProcessRequest {
      val command = pigeonVar_list[0] as String
      val args = pigeonVar_list[1] as List<String>
      val cwd = pigeonVar_list[2] as String?
      val environment = pigeonVar_list[3] as Map<String, String>?
      return ProcessRequest(command, args, cwd, environment)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      command,
      args,
      cwd,
      environment,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProcessRequest
    return IdeApiPigeonUtils.deepEquals(this.command, other.command) && IdeApiPigeonUtils.deepEquals(this.args, other.args) && IdeApiPigeonUtils.deepEquals(this.cwd, other.cwd) && IdeApiPigeonUtils.deepEquals(this.environment, other.environment)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.command)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.args)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.cwd)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.environment)
    return result
  }
  override fun toString(): String {
    return "ProcessRequest(command=$command, args=$args, cwd=$cwd, environment=$environment)"
  }
}

/**
 * An opened project.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProjectInfo (
  val name: String,
  val path: String,
  val language: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProjectInfo {
      val name = pigeonVar_list[0] as String
      val path = pigeonVar_list[1] as String
      val language = pigeonVar_list[2] as String?
      return ProjectInfo(name, path, language)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      path,
      language,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProjectInfo
    return IdeApiPigeonUtils.deepEquals(this.name, other.name) && IdeApiPigeonUtils.deepEquals(this.path, other.path) && IdeApiPigeonUtils.deepEquals(this.language, other.language)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.name)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.path)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.language)
    return result
  }
  override fun toString(): String {
    return "ProjectInfo(name=$name, path=$path, language=$language)"
  }
}

/**
 * A filesystem entry listing.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FileEntry (
  val name: String,
  val path: String,
  val isDirectory: Boolean,
  val size: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FileEntry {
      val name = pigeonVar_list[0] as String
      val path = pigeonVar_list[1] as String
      val isDirectory = pigeonVar_list[2] as Boolean
      val size = pigeonVar_list[3] as Long?
      return FileEntry(name, path, isDirectory, size)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      path,
      isDirectory,
      size,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FileEntry
    return IdeApiPigeonUtils.deepEquals(this.name, other.name) && IdeApiPigeonUtils.deepEquals(this.path, other.path) && IdeApiPigeonUtils.deepEquals(this.isDirectory, other.isDirectory) && IdeApiPigeonUtils.deepEquals(this.size, other.size)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.name)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.path)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.isDirectory)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.size)
    return result
  }
  override fun toString(): String {
    return "FileEntry(name=$name, path=$path, isDirectory=$isDirectory, size=$size)"
  }
}

/**
 * Git working tree status.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class GitStatus (
  val branch: String,
  val modified: List<String>,
  val added: List<String>,
  val deleted: List<String>,
  val untracked: List<String>,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GitStatus {
      val branch = pigeonVar_list[0] as String
      val modified = pigeonVar_list[1] as List<String>
      val added = pigeonVar_list[2] as List<String>
      val deleted = pigeonVar_list[3] as List<String>
      val untracked = pigeonVar_list[4] as List<String>
      val error = pigeonVar_list[5] as String?
      return GitStatus(branch, modified, added, deleted, untracked, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      branch,
      modified,
      added,
      deleted,
      untracked,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GitStatus
    return IdeApiPigeonUtils.deepEquals(this.branch, other.branch) && IdeApiPigeonUtils.deepEquals(this.modified, other.modified) && IdeApiPigeonUtils.deepEquals(this.added, other.added) && IdeApiPigeonUtils.deepEquals(this.deleted, other.deleted) && IdeApiPigeonUtils.deepEquals(this.untracked, other.untracked) && IdeApiPigeonUtils.deepEquals(this.error, other.error)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.branch)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.modified)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.added)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.deleted)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.untracked)
    result = 31 * result + IdeApiPigeonUtils.deepHash(this.error)
    return result
  }
  override fun toString(): String {
    return "GitStatus(branch=$branch, modified=$modified, added=$added, deleted=$deleted, untracked=$untracked, error=$error)"
  }
}
private open class IdeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetupStatus.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RuntimeInfo.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProcessRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProjectInfo.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FileEntry.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GitStatus.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SetupStatus -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RuntimeInfo -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ProcessInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ProcessRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ProjectInfo -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is FileEntry -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is GitStatus -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SetupApi {
  fun getStatus(): SetupStatus
  fun startSetup()

  companion object {
    /** The codec used by SetupApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `SetupApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SetupApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.SetupApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.SetupApi.startSetup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startSetup()
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RuntimeApi {
  fun getRuntimes(): List<RuntimeInfo>
  fun getRuntime(id: String): RuntimeInfo
  fun installRuntime(id: String)
  fun uninstallRuntime(id: String)
  fun updateRuntime(id: String)

  companion object {
    /** The codec used by RuntimeApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `RuntimeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RuntimeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.RuntimeApi.getRuntimes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRuntimes())
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.RuntimeApi.getRuntime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getRuntime(idArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.RuntimeApi.installRuntime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.installRuntime(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.RuntimeApi.uninstallRuntime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.uninstallRuntime(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.RuntimeApi.updateRuntime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.updateRuntime(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TerminalApi {
  fun createSession(cwd: String, cols: Long, rows: Long): String
  fun write(sessionId: String, data: String)
  fun resize(sessionId: String, cols: Long, rows: Long)
  fun close(sessionId: String)
  fun sendSignal(sessionId: String, signal: String)

  companion object {
    /** The codec used by TerminalApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `TerminalApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TerminalApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.TerminalApi.createSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cwdArg = args[0] as String
            val colsArg = args[1] as Long
            val rowsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              listOf(api.createSession(cwdArg, colsArg, rowsArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.TerminalApi.write$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val dataArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.write(sessionIdArg, dataArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.TerminalApi.resize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val colsArg = args[1] as Long
            val rowsArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.resize(sessionIdArg, colsArg, rowsArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.TerminalApi.close$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.close(sessionIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.TerminalApi.sendSignal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val signalArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.sendSignal(sessionIdArg, signalArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProcessApi {
  fun startProcess(request: ProcessRequest): ProcessInfo
  fun killProcess(pid: String)
  fun listProcesses(): List<ProcessInfo>

  companion object {
    /** The codec used by ProcessApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `ProcessApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProcessApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProcessApi.startProcess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ProcessRequest
            val wrapped: List<Any?> = try {
              listOf(api.startProcess(requestArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProcessApi.killProcess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pidArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.killProcess(pidArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProcessApi.listProcesses$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listProcesses())
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProjectApi {
  fun createProject(name: String, language: String): ProjectInfo
  fun listProjects(): List<ProjectInfo>
  fun openProject(path: String)
  fun deleteProject(path: String)

  companion object {
    /** The codec used by ProjectApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `ProjectApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProjectApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProjectApi.createProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val languageArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.createProject(nameArg, languageArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProjectApi.listProjects$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listProjects())
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProjectApi.openProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.openProject(pathArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.ProjectApi.deleteProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.deleteProject(pathArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FileApi {
  fun readFile(path: String): String
  fun writeFile(path: String, content: String)
  fun listFiles(path: String): List<FileEntry>
  fun rename(oldPath: String, newPath: String): Boolean
  fun delete(path: String): Boolean
  fun mkdir(path: String): Boolean

  companion object {
    /** The codec used by FileApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `FileApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FileApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.FileApi.readFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.readFile(pathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.FileApi.writeFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val contentArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.writeFile(pathArg, contentArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.FileApi.listFiles$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.listFiles(pathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.FileApi.rename$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val oldPathArg = args[0] as String
            val newPathArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.rename(oldPathArg, newPathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.FileApi.delete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.delete(pathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.FileApi.mkdir$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.mkdir(pathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GitApi {
  fun status(projectPath: String): GitStatus
  fun add(projectPath: String, paths: List<String>)
  fun commit(projectPath: String, message: String)
  fun diff(projectPath: String): String

  companion object {
    /** The codec used by GitApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `GitApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: GitApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.GitApi.status$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val projectPathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.status(projectPathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.GitApi.add$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val projectPathArg = args[0] as String
            val pathsArg = args[1] as List<String>
            val wrapped: List<Any?> = try {
              api.add(projectPathArg, pathsArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.GitApi.commit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val projectPathArg = args[0] as String
            val messageArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.commit(projectPathArg, messageArg)
              listOf(null)
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.GitApi.diff$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val projectPathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.diff(projectPathArg))
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WebPreviewApi {
  fun previewUrl(): String?

  companion object {
    /** The codec used by WebPreviewApi. */
    val codec: MessageCodec<Any?> by lazy {
      IdeApiPigeonCodec()
    }
    /** Sets up an instance of `WebPreviewApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WebPreviewApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.codeide.WebPreviewApi.previewUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.previewUrl())
            } catch (exception: Throwable) {
              IdeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
